### PR TITLE
Assorted nits and suggestions

### PR DESCRIPTION
**Pull request by thaJeztah**
Relates to https://github.com/docker/cli/pull/4226#pullrequestreview-1462339508

### CODE REVIEW

**Comment by thaJeztah** [comment]
@laurazard let me know if these make sense 😅

**Review by laurazard — APPROVED** [review]

**Comment by laurazard** [comment]
Thank you @thaJeztah!! Sorry for the delay looking at this 😓

**Comment by thaJeztah** [comment]
No worries! Wasn't sure if you noticed this one (I personally always overlook PR's in my own namespace on GitHub 😂)

**Comment by laurazard** [comment]
No, I totally missed it 😅

**Pull request merged**
